Fix misconfiguration

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -12,14 +12,24 @@ jobs:
         uses: actions/checkout@v2
       - name: Health
         run: |
-          home_route="$(curl https://trevordmiller.com)"
-          if [[ $home_route != *"My posts about software development."* ]]; then
-            echo "ERROR: The home route is not working as expected!";
+          home_route="$(curl -L https://trevordmiller.com)"
+          if [[ $home_route != *"My writing about software development."* ]]; then
+            echo "ERROR: The home route redirect to /writing/ is not working as expected!";
             exit 1;
           fi
-          article_route="$(curl https://trevordmiller.com/programming-principles/)"
-          if [[ $article_route != *"My guiding principles for software development in general."* ]]; then
-            echo "ERROR: The article routes are not working as expected!";
+          writing_route="$(curl https://trevordmiller.com/writing/)"
+          if [[ $writing_route != *"My writing about software development."* ]]; then
+            echo "ERROR: The writing route is not working as expected!";
+            exit 1;
+          fi
+          individual_writing_route="$(curl https://trevordmiller.com/writing/programming-principles/)"
+          if [[ $individual_writing_route != *"My guiding principles for software development in general."* ]]; then
+            echo "ERROR: The individual writing route is not working as expected!";
+            exit 1;
+          fi
+          newsletter_route="$(curl https://trevordmiller.com/newsletter/)"
+          if [[ $newsletter_route != *"My email list."* ]]; then
+            echo "ERROR: The newsletter route is not working as expected!";
             exit 1;
           fi
           about_route="$(curl https://trevordmiller.com/about/)"
@@ -27,12 +37,12 @@ jobs:
             echo "ERROR: The about route is not working as expected!";
             exit 1;
           fi
-          resume_route="$(curl https://trevordmiller.com/resume/)"
+          resume_route="$(curl https://trevordmiller.com/about/resume/)"
           if [[ $resume_route != *"My professional background."* ]]; then
             echo "ERROR: The resume route is not working as expected!";
             exit 1;
           fi
-          projects_route="$(curl https://trevordmiller.com/projects/)"
+          projects_route="$(curl https://trevordmiller.com/about/projects/)"
           if [[ $projects_route != *"My open source projects."* ]]; then
             echo "ERROR: The projects route is not working as expected!";
             exit 1;
@@ -51,7 +61,9 @@ jobs:
           runs: 3
           urls: |
             https://trevordmiller.com
-            https://trevordmiller.com/programming-principles/
+            https://trevordmiller.com/writing/
+            https://trevordmiller.com/writing/programming-principles/
+            https://trevordmiller.com/newsletter/
             https://trevordmiller.com/about/
-            https://trevordmiller.com/resume/
-            https://trevordmiller.com/projects/
+            https://trevordmiller.com/about/resume/
+            https://trevordmiller.com/about/projects/
