Flatten pages

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -13,9 +13,29 @@ jobs:
         uses: actions/checkout@v2
       - name: Test
         run: |
-          website_document="$(curl https://trevordmiller.com)"
-          if [[ $website_document != *"Join my newsletter"* ]]; then
-            echo "ERROR: https://trevordmiller.com is not running as expected!";
+          articles_page="$(curl https://trevordmiller.com)"
+          if [[ $articles_page != *"My posts about software development."* ]]; then
+            echo "ERROR: The articles index page is not running as expected!";
+            exit 1;
+          fi
+          article_page="$(curl https://trevordmiller.com/standard-vim)"
+          if [[ $article_page != *"Using Vim without customizations."* ]]; then
+            echo "ERROR: The individual article pages are not running as expected!";
+            exit 1;
+          fi
+          projects_page="$(curl https://trevordmiller.com/projects)"
+          if [[ $projects_page != *"My open source code."* ]]; then
+            echo "ERROR: The projects page is not running as expected!";
+            exit 1;
+          fi
+          about_page="$(curl https://trevordmiller.com/about)"
+          if [[ $about_page != *"My personal background."* ]]; then
+            echo "ERROR: The about page is not running as expected!";
+            exit 1;
+          fi
+          resume_page="$(curl https://trevordmiller.com/resume)"
+          if [[ $resume_page != *"My professional background."* ]]; then
+            echo "ERROR: The resume page is not running as expected!";
             exit 1;
           fi
       - name: Audit
@@ -27,4 +47,6 @@ jobs:
           urls: |
             https://trevordmiller.com
             https://trevordmiller.com/standard-vim/
+            https://trevordmiller.com/projects/
+            https://trevordmiller.com/about/
             https://trevordmiller.com/resume/
